import { Injectable } from '@angular/core';
import { IDispatchRanking } from '../models/dispatch.ranking.model';
import { IDate } from '../models/date.model';
import { IDispatch } from '../models/dispatch.model';
import { SidebarData } from '../models/sidebar.data.model';

@Injectable({
  providedIn: 'root',
})
export class DataService {
  constructor() {}

  private dispatchRankings: IDispatchRanking[] = [
    {
      id: 1,
      dispatcher: 'Luka Sekulic',
      trucks: 9.5,
      gross: 58.276,
      firstI: 3.67,
      RPM: 2.31,
      secondI: 5.47,
      mileage: 25.256,
      grosPerTruck: 6.134,
      thirdI: 3.66,
    },
    {
      id: 2,
      dispatcher: 'Milos Ivankovic',
      trucks: 9,
      gross: 55.887,
      firstI: -0.59,
      RPM: 2.12,
      secondI: -4.0,
      mileage: 26.298,
      grosPerTruck: 6.208,
      thirdI: 4.91,
    },
    {
      id: 3,
      dispatcher: 'Nemanja Dimitrijevic',
      trucks: 9.3,
      gross: 54.485,
      firstI: -3.08,
      RPM: 2.16,
      secondI: -1.36,
      mileage: 25.267,
      grosPerTruck: 5.858,
      thirdI: -0.99,
    },
    {
      id: 0,
      dispatcher: 'Top 3 Average',
      trucks: 9.5,
      gross: 56.212,
      firstI: 0,
      RPM: 2.19,
      secondI: 0,
      mileage: 25.607,
      grosPerTruck: 5.917,
      thirdI: 0,
    },
    {
      id: 4,
      dispatcher: 'Luka Stojkovic',
      trucks: 9.5,
      gross: 51.515,
      firstI: -8.56,
      RPM: 2.12,
      secondI: -4.0,
      mileage: 24.334,
      grosPerTruck: 5.422,
      thirdI: -8.36,
    },
    {
      id: 5,
      dispatcher: 'Svetozar Milovanovic',
      trucks: 9,
      gross: 50.15,
      firstI: -11.79,
      RPM: 2.03,
      secondI: -7.3,
      mileage: 24.71,
      grosPerTruck: 5.572,
      thirdI: -5.83,
    },
    {
      id: 6,
      dispatcher: 'Filip Stojanovic',
      trucks: 9.3,
      gross: 49.055,
      firstI: -12.74,
      RPM: 2.11,
      secondI: -3.65,
      mileage: 23.248,
      grosPerTruck: 5.274,
      thirdI: -10.86,
    },
    {
      id: 7,
      dispatcher: 'Todor Stepanovic',
      trucks: 9.5,
      gross: 45.758,
      firstI: -18.6,
      RPM: 2.14,
      secondI: -2.28,
      mileage: 21.37,
      grosPerTruck: 4.73,
      thirdI: -20.06,
    },
  ];

  private dates: IDate[] = [
    {
      hedline: 'This week',
      centralNumber: 46,
      leftValue: 6.85,
      rightValue: 2.18,
    },
    {
      hedline: 'Jul 1 - Jul 7',
      centralNumber: 46,
      leftValue: 6.85,
      rightValue: 2.18,
    },
    {
      hedline: 'Jun 24 - Jun 30',
      centralNumber: 46,
      leftValue: 6.85,
      rightValue: 2.18,
    },
    {
      hedline: 'Jun 17 - Jun 23',
      centralNumber: 46,
      leftValue: 6.85,
      rightValue: 2.18,
    },
    {
      hedline: 'Jun 10 - Jun 16',
      centralNumber: 46,
      leftValue: 6.85,
      rightValue: 2.18,
    },
  ];

  private dispatchs: IDispatch[] = [
    {
      name: 'Frederick',
      lastName: 'Robinson',
      shortName: 'Greg R.',
      sddc: 7994,
      gross: 56,
      RPM: 87,
      miles: 2.527,
      topSalary: 5.46,
      botSalary: 2.16,
      isChecked: false,
      points: 14,
    },
    {
      name: 'Frederick',
      lastName: 'Robinson',
      shortName: 'Greg R.',
      sddc: 7994,
      gross: 106,
      RPM: 102,
      miles: 3.273,
      topSalary: 7.3,
      botSalary: 2.23,
      isChecked: true,
      points: 28,
    },
    {
      name: 'Frederick',
      lastName: 'Robinson',
      shortName: 'Greg R.',
      sddc: 7994,
      gross: 94,
      RPM: 87,
      miles: 2.527,
      topSalary: 5.46,
      botSalary: 2.16,
      isChecked: false,
      points: 18,
    },
    {
      name: 'Frederick',
      lastName: 'Robinson',
      shortName: 'Greg R.',
      sddc: 7994,
      gross: 100,
      RPM: 100,
      miles: 3.273,
      topSalary: 7.3,
      botSalary: 2.23,
      isChecked: true,
      points: 20,
    },
  ];

  private sidebarData: SidebarData[] = [
    {
      dispatcher: 'Greg',
      targetAchieved: 9,
      earnings: 900,
      grossPts: 216,
      RPMPts: 216,
      totalPts: 216,
    },
    {
      dispatcher: 'Filip',
      targetAchieved: 9,
      earnings: 850,
      grossPts: 208,
      RPMPts: 208,
      totalPts: 208,
    },
    {
      dispatcher: 'Blake',
      targetAchieved: 9,
      earnings: 850,
      grossPts: 194,
      RPMPts: 194,
      totalPts: 194,
    },
    {
      dispatcher: 'Rob',
      targetAchieved: 9,
      earnings: 800,
      grossPts: 192,
      RPMPts: 192,
      totalPts: 192,
    },
    {
      dispatcher: 'Beka',
      targetAchieved: 9,
      earnings: 750,
      grossPts: 175,
      RPMPts: 175,
      totalPts: 175,
    },
    {
      dispatcher: 'Jason',
      targetAchieved: 9,
      earnings: 700,
      grossPts: 172,
      RPMPts: 172,
      totalPts: 172,
    },
    {
      dispatcher: 'Ben',
      targetAchieved: 9,
      earnings: 650,
      grossPts: 162,
      RPMPts: 162,
      totalPts: 162,
    },
    {
      dispatcher: 'Gary',
      targetAchieved: 9,
      earnings: 600,
      grossPts: 152,
      RPMPts: 152,
      totalPts: 152,
    },
    {
      dispatcher: 'Greg',
      targetAchieved: 9,
      earnings: 900,
      grossPts: 216,
      RPMPts: 216,
      totalPts: 216,
    },
    {
      dispatcher: 'Filip',
      targetAchieved: 9,
      earnings: 850,
      grossPts: 208,
      RPMPts: 208,
      totalPts: 208,
    },
    {
      dispatcher: 'Blake',
      targetAchieved: 9,
      earnings: 850,
      grossPts: 194,
      RPMPts: 194,
      totalPts: 194,
    },
    {
      dispatcher: 'Rob',
      targetAchieved: 9,
      earnings: 800,
      grossPts: 192,
      RPMPts: 192,
      totalPts: 192,
    },
    {
      dispatcher: 'Beka',
      targetAchieved: 9,
      earnings: 750,
      grossPts: 175,
      RPMPts: 175,
      totalPts: 175,
    },
    {
      dispatcher: 'Jason',
      targetAchieved: 9,
      earnings: 700,
      grossPts: 172,
      RPMPts: 172,
      totalPts: 172,
    },
    {
      dispatcher: 'Ben',
      targetAchieved: 9,
      earnings: 650,
      grossPts: 162,
      RPMPts: 162,
      totalPts: 162,
    },
    {
      dispatcher: 'Gary',
      targetAchieved: 9,
      earnings: 600,
      grossPts: 152,
      RPMPts: 152,
      totalPts: 152,
    },
    {
      dispatcher: 'Ben',
      targetAchieved: 9,
      earnings: 650,
      grossPts: 162,
      RPMPts: 162,
      totalPts: 162,
    },
    {
      dispatcher: 'Gary',
      targetAchieved: 9,
      earnings: 600,
      grossPts: 152,
      RPMPts: 152,
      totalPts: 152,
    },
    {
      dispatcher: 'Greg',
      targetAchieved: 9,
      earnings: 900,
      grossPts: 216,
      RPMPts: 216,
      totalPts: 216,
    },
    {
      dispatcher: 'Filip',
      targetAchieved: 9,
      earnings: 850,
      grossPts: 208,
      RPMPts: 208,
      totalPts: 208,
    },
    {
      dispatcher: 'Blake',
      targetAchieved: 9,
      earnings: 850,
      grossPts: 194,
      RPMPts: 194,
      totalPts: 194,
    },
    {
      dispatcher: 'Rob',
      targetAchieved: 9,
      earnings: 800,
      grossPts: 192,
      RPMPts: 192,
      totalPts: 192,
    },
    {
      dispatcher: 'Beka',
      targetAchieved: 9,
      earnings: 750,
      grossPts: 175,
      RPMPts: 175,
      totalPts: 175,
    },
    {
      dispatcher: 'Jason',
      targetAchieved: 9,
      earnings: 700,
      grossPts: 172,
      RPMPts: 172,
      totalPts: 172,
    },
    {
      dispatcher: 'Ben',
      targetAchieved: 9,
      earnings: 650,
      grossPts: 162,
      RPMPts: 162,
      totalPts: 162,
    },
    {
      dispatcher: 'Gary',
      targetAchieved: 9,
      earnings: 600,
      grossPts: 152,
      RPMPts: 152,
      totalPts: 152,
    },
  ];

  getDispatchRankings(): IDispatchRanking[] {
    return this.dispatchRankings.slice();
  }

  getDates(): IDate[] {
    return this.dates.slice();
  }

  getDispatchs(): IDispatch[] {
    return this.dispatchs.slice();
  }

  getSidebarData(): SidebarData[] {
    return this.sidebarData.slice();
  }
}
